### ISSUE TITLE
Vote for release from testing branch

### ISSUE THREAD

**Issue by SteveSimpson** [iusrepo/php74-pecl-yaml#1]
Not sure the procedure, but I'm throwing in a vote for this to be released to the production branch. It is certainly working as expected for me.

**Comment by carlwgeorge** [comment]
Sorry we missed this.  Looks like php74-pecl-yaml-2.1.0-3.el7.ius was pushed to the main repo on [2020-12-08](https://github.com/iusrepo/wishlist/issues/282#issuecomment-740785197).  Voting for the initial build usually happens in the wishlist issue requesting the package.  After that opening an issue like this is fine if you can't find an existing one for the new version.
